version: "1.1"

on:
  push:
    branches:
      - release/*
    tags:
      - v*

stages:
  - stage:
      - git-checkout:
          alias: fluent-bit
          params:
            depth: 1
  - stage:
      - extract-repo-version:
          params:
            git_dir: ${{ dirs.fluent-bit }}
  - stage:
      - custom-script:
          alias: build-fluent-bit
          commands:
            - cd ${{ dirs.fluent-bit }}
            - echo $(pwd)
            - echo $(ls)
            - export DOCKER_REGISTRY=${{ configs.docker_registry }}
            - export DOCKER_REGISTRY_USERNAME=${{ configs.docker_registry_username }}
            - export DOCKER_REGISTRY_PASSWORD=${{ configs.docker_registry_password }}
            - export IMAGE_TAG=${{ outputs.extract-repo-version.image_tag }}
            - ./build.sh
          resources:
            cpu: 2
            mem: 2048
  - stage:
      - release:
          alias: release-fluent-bit
          params:
            check_diceyml: false
            dice_yml: ${{ dirs.fluent-bit }}/erda.yml
            image:
              fluent-bit: ${{ outputs.build-fluent-bit.image }}
              fluent-bit-app: ${{ outputs.build-fluent-bit.image }}
